GET http://localhost:5000/admin/loggedin

###

GET http://localhost:5000/users/loggin/

###

POST http://localhost:5000/users/add
content-type: application/json
{
     "firstName": "Elin",
     "lastName": "olssson",
     "email": "Elin@mail.com",
     "passWord": "hejhej123",
     "newsLetter": true
}

###

POST http://localhost:5000/users/loggin
content-type: application/json

{
     "email": "Elin@mail.com",
     "passWord": "hejhej123"
}

###

PUT http://localhost:5000/users/acceptnews
content-type: application/json

{
     "_id": "628f315415a9c0c65ad3031e",
     "newsLetter": true
}